# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(default='默认的', max_length=30, verbose_name='组名')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='帐号')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('name', models.CharField(max_length=30, verbose_name='昵称')),
                ('sex', models.CharField(default='男', max_length=6, verbose_name='性别')),
                ('hometown', models.CharField(blank=True, max_length=20, verbose_name='籍贯')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='地址')),
                ('birth', models.CharField(max_length=10, verbose_name='出生年月')),
                ('desc', models.TextField(blank=True, verbose_name='个人描述')),
                ('imageid', models.CharField(blank=True, max_length=50, verbose_name='头像ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('is_login', models.BooleanField(default=False, verbose_name='是否在线')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP地址')),
                ('ip_local', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='内网IP地址')),
                ('local_port', models.CharField(blank=True, max_length=8, verbose_name='内网ip地址端口号')),
                ('android_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='内网IP地址')),
                ('android_port', models.CharField(blank=True, max_length=8)),
                ('pcstate', models.CharField(blank=True, max_length=4)),
                ('adstate', models.CharField(blank=True, max_length=4)),
                ('friends', models.ManyToManyField(blank=True, null=True, to='miniqq.Friend', verbose_name='好友')),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miniqq.User', verbose_name='用户名'),
        ),
    ]
